modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="customblocksmod"
version="1.0.0"
displayName="Custom Blocks Mod"
authors="you"
description='''
500 максимально банальных блоков с разными текстурами.
'''
